name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UC92tkRtkVMRKvH8_prEzBtQ
          max_videos: 6
          theme_context_dark: '{ "background_color": "#0d1117", "title_color": "#ffffff", "stats_color": "#dedede" }'
          commit_message: "docs(readme): Update YouTube cards"
          readme_path: readme.md
